[package]
name = "fowin-test-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
fowin = { path = "../../" }
rand = "0.8.5"
# TODO: use rkyv
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
interprocess = "2.1.0"
